# Generated by Django 5.1.1 on 2024-09-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
